theme = "awesome-identity"
baseURL = "https://calebstew.art"
title = "$ uname -a"
publishDir = "docs"
disableKinds = ["taxonomy", "term"]

## Profile Configurations
[params.profile]
  portrait = "/images/portrait.png"
  firstname = "Caleb"
  lastname = "Stewart"
  title = "Software Engineer, Penetration Tester, Reverse Engineer"
  location = "College Park, MD"
  bio = """I am a software engineer and cyber security expert with experience in many programming languages. I have over ten years of software development experience. I love systems programming languages, but have written applications at many layers from Assembly to Javascript (to my own dismay). I am passionate about creating simple, elegant and abstract frameworks to automate as much as possible. In my day job, I have experience in the Security Operations Center, Incident Response and Red Team."""

[params.contacts]
  email = "caleb.stewart94@gmail.com"
  github = "calebstewart"
  gitlab = "caleb.stewart"
  linkedin = "calebjstewart"
  twitter = "calebjstewart"

[params.actions.resume]
  name = "Resume"
  url = "/resume"

[params.actions.source]
  name = "Site Source"
  url = "https://github.com/calebstewart/calebstew.art"

## Footer Configurations
[params.footer]
  copyright = """<i class="fab fa-linux"></i> *i use [arch](https://archlinux.org), btw* <i class="fab fa-linux"></i>"""
  poweredBy = true

[markup.goldmark.renderer]
unsafe= true
